/**
 * Development mock data — returned by services when USE_MOCK_DATA=true.
 * shapes mirror what Prisma returns from RecordsService.findAll/findOne
 * after the `include` clauses (uploadedBy, archivedBy, auditLogs->user).
 */

import {
  AnalysisStatus,
  RetentionStatus,
  UserRole,
  VisitorType,
} from '@/generated/prisma/enums';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface MockUser {
  id: string;
  name: string;
  email: string;
  passwordHash: string; // bcrypt of "senhaSegura123", 12 rounds
  roles: UserRole[];
  active: boolean;
  lastLogin: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface MockAuditLog {
  id: string;
  recordId: string | null;
  userId: string;
  user: { id: string; name: string; roles: UserRole[] };
  action: string;
  previousStatus: AnalysisStatus | null;
  nextStatus: AnalysisStatus | null;
  notes: string | null;
  createdAt: Date;
}

export interface MockRecord {
  id: string;
  detaineeName: string;
  detaineeCode: string | null;
  detaineeCell: string | null;
  visitorName: string;
  visitorType: VisitorType;
  unit: string;
  vivencia: string | null;
  equipment: string;
  blobUrl: string | null;
  mediaAvailable: boolean;
  recordedAt: Date;
  uploadedAt: Date;
  uploadedById: string;
  uploadedBy: { id: string; name: string };
  analysisStatus: AnalysisStatus;
  retentionStatus: RetentionStatus;
  aiScore: number | null;
  analystId: string | null;
  analystDecision: string | null;
  analystJustification: string | null;
  analysisConfirmedAt: Date | null;
  supervisorId: string | null;
  supervisorDecision: string | null;
  supervisorJustification: string | null;
  supervisorDecidedAt: Date | null;
  transcription: unknown;
  canonicalAnalysis: unknown;
  archivedAt: Date | null;
  archivedById: string | null;
  archivedBy: { id: string; name: string; roles: UserRole[] } | null;
  auditLogs: MockAuditLog[];
  createdAt: Date;
  updatedAt: Date;
}

// ─── Mock Users ───────────────────────────────────────────────────────────────
// All users share the same password: "senhaSegura123"
// The hash below is bcrypt(12 rounds) of that password — generated by seed.ts.
// This is used when returning users from the mock; auth always hits the real DB
// (seeded via `npm run db:seed`).

export const MOCK_USERS: MockUser[] = [
  {
    id: 'mock-u1',
    name: 'Ana Silva',
    email: 'ana.silva@sistema.gov.br',
    passwordHash: '$2b$12$placeholderHashForMockUser1xxxxxxxxxxxxxxxxxxxxxxxxxx',
    roles: [UserRole.supervisor, UserRole.admin],
    active: true,
    lastLogin: new Date('2026-02-19T10:30:00'),
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-02-19'),
  },
  {
    id: 'mock-u2',
    name: 'Pedro Rocha',
    email: 'pedro.rocha@sistema.gov.br',
    passwordHash: '$2b$12$placeholderHashForMockUser2xxxxxxxxxxxxxxxxxxxxxxxxxx',
    roles: [UserRole.analyst],
    active: true,
    lastLogin: new Date('2026-02-19T09:15:00'),
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-02-19'),
  },
  {
    id: 'mock-u3',
    name: 'Carlos Lima',
    email: 'carlos.lima@sistema.gov.br',
    passwordHash: '$2b$12$placeholderHashForMockUser3xxxxxxxxxxxxxxxxxxxxxxxxxx',
    roles: [UserRole.uploader],
    active: true,
    lastLogin: new Date('2026-02-18T17:00:00'),
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-02-18'),
  },
  {
    id: 'mock-u4',
    name: 'Fernanda Costa',
    email: 'fernanda.costa@sistema.gov.br',
    passwordHash: '$2b$12$placeholderHashForMockUser4xxxxxxxxxxxxxxxxxxxxxxxxxx',
    roles: [UserRole.analyst, UserRole.supervisor],
    active: true,
    lastLogin: new Date('2026-02-17T11:00:00'),
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-02-17'),
  },
  {
    id: 'mock-u5',
    name: 'Marcos Teixeira',
    email: 'marcos.t@sistema.gov.br',
    passwordHash: '$2b$12$placeholderHashForMockUser5xxxxxxxxxxxxxxxxxxxxxxxxxx',
    roles: [UserRole.uploader],
    active: false,
    lastLogin: new Date('2026-02-15T08:00:00'),
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'mock-u6',
    name: 'Juliana Neves',
    email: 'juliana.n@sistema.gov.br',
    passwordHash: '$2b$12$placeholderHashForMockUser6xxxxxxxxxxxxxxxxxxxxxxxxxx',
    roles: [UserRole.analyst],
    active: true,
    lastLogin: new Date('2026-02-19T08:45:00'),
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-02-19'),
  },
];

// Convenient lookup map
export const MOCK_USER_MAP = Object.fromEntries(MOCK_USERS.map((u) => [u.id, u]));

// ─── Mock Records ─────────────────────────────────────────────────────────────

/** Full transcription payload for record REC-00129 */
const TRANSCRIPTION_REC00129 = {
  lines: [
    { timestamp: '00:00', speaker: 'Advogado', text: 'Bom dia, João. Como você está passando?' },
    { timestamp: '00:05', speaker: 'Detento', text: 'Bom dia, doutor. Tô indo, dentro do possível.' },
    { timestamp: '00:10', speaker: 'Advogado', text: 'Temos novidades sobre o caso. O juiz marcou audiência para a semana que vem.' },
    { timestamp: '00:18', speaker: 'Detento', text: 'E como tá a situação? A encomenda que a gente conversou chegou?' },
    { timestamp: '00:24', speaker: 'Advogado', text: 'Sim, o processo tá andando. Precisamos falar sobre o pacote de documentos que precisa ser preparado.' },
    { timestamp: '00:31', speaker: 'Detento', text: 'Entendido. O pacote vai ser recebido no dia combinado então.' },
    { timestamp: '00:38', speaker: 'Advogado', text: 'Exatamente. Mais alguma coisa que você precise?' },
    { timestamp: '00:42', speaker: 'Detento', text: 'Por enquanto não, doutor. Aguardo as novidades.' },
    { timestamp: '00:48', speaker: 'Advogado', text: 'Certo. Vou precisar que você assine uns papéis na próxima visita.' },
    { timestamp: '00:55', speaker: 'Detento', text: 'Pode trazer que eu assino. É sobre aquele recurso?' },
    { timestamp: '01:02', speaker: 'Advogado', text: 'Isso, é a petição de progressão de regime. Já montei toda a argumentação.' },
    { timestamp: '01:10', speaker: 'Detento', text: 'E o doutor acha que tem chance de sair?' },
    { timestamp: '01:16', speaker: 'Advogado', text: 'O comportamento tá bom, já cumpriu o tempo mínimo. Acho que tem boas chances.' },
    { timestamp: '01:25', speaker: 'Detento', text: 'Minha mãe tá preocupada, doutor. Ela ligou pra saber do andamento.' },
    { timestamp: '01:33', speaker: 'Advogado', text: 'Conversei com ela ontem. Expliquei a situação, ela ficou mais tranquila.' },
    { timestamp: '01:40', speaker: 'Detento', text: 'Agradeço, doutor. Ela é idosa, não entende muito dessas coisas.' },
    { timestamp: '01:48', speaker: 'Advogado', text: 'Sem problema. Agora, sobre o trabalho interno, você continua na oficina?' },
    { timestamp: '01:55', speaker: 'Detento', text: 'Sim, tô na marcenaria. O diretor falou que vai me dar um certificado.' },
    { timestamp: '02:03', speaker: 'Advogado', text: 'Ótimo, isso ajuda muito no processo. Vou anexar como prova de ressocialização.' },
    { timestamp: '02:12', speaker: 'Detento', text: 'E aquela parada do curso que eu pedi? Conseguiu ver?' },
    { timestamp: '02:18', speaker: 'Advogado', text: 'Sim, o curso de informática vai começar mês que vem. Já coloquei seu nome na lista.' },
    { timestamp: '02:26', speaker: 'Detento', text: 'Boa! Isso aí vai me ajudar quando eu sair daqui.' },
    { timestamp: '02:33', speaker: 'Advogado', text: 'Com certeza. Educação e trabalho são diferenciais pra progressão.' },
    { timestamp: '02:40', speaker: 'Detento', text: 'Doutor, e sobre a visita da minha família? Minha esposa tá com dificuldade pra vir.' },
    { timestamp: '02:49', speaker: 'Advogado', text: 'Qual a dificuldade? É questão de transporte?' },
    { timestamp: '02:55', speaker: 'Detento', text: 'É, ela mora longe e não tem como vir toda semana. Queria ver se dá pra pedir visita virtual.' },
    { timestamp: '03:04', speaker: 'Advogado', text: 'Dá sim, vou entrar com o pedido. A unidade já tem estrutura pra videoconferência.' },
    { timestamp: '03:12', speaker: 'Detento', text: 'Isso seria bom demais. As crianças tão com saudade.' },
    { timestamp: '03:18', speaker: 'Advogado', text: 'Vou agilizar. Agora preciso ir, tenho outra audiência agora à tarde.' },
    { timestamp: '03:25', speaker: 'Detento', text: 'Tá bom, doutor. Valeu pela visita. Deus abençoe.' },
    { timestamp: '03:30', speaker: 'Advogado', text: 'Qualquer novidade eu mando recado. Fique bem, João.' },
    { timestamp: '03:35', speaker: 'Detento', text: 'Obrigado, doutor. Até a próxima.' },
  ],
  canonicalLines: [
    { timestamp: '00:00', speaker: 'Advogado', text: 'Bom dia, João. Como você está passando?' },
    { timestamp: '00:05', speaker: 'Detento', text: 'Bom dia, doutor. Estou indo, dentro do possível.' },
    { timestamp: '00:10', speaker: 'Advogado', text: 'Temos novidades sobre o caso. O juiz marcou audiência para a semana que vem.' },
    { timestamp: '00:18', speaker: 'Detento', text: 'E como está a situação? A encomenda sobre a qual conversamos chegou?' },
    { timestamp: '00:24', speaker: 'Advogado', text: 'Sim, o processo está andando. Precisamos falar sobre o pacote de documentos que precisa ser preparado.' },
    { timestamp: '00:31', speaker: 'Detento', text: 'Entendido. O pacote será recebido no dia combinado, então.' },
    { timestamp: '00:38', speaker: 'Advogado', text: 'Exatamente. Mais alguma coisa de que você precise?' },
    { timestamp: '00:42', speaker: 'Detento', text: 'Por enquanto não, doutor. Aguardo as novidades.' },
    { timestamp: '00:48', speaker: 'Advogado', text: 'Certo. Vou precisar que você assine alguns documentos na próxima visita.' },
    { timestamp: '00:55', speaker: 'Detento', text: 'Pode trazer que eu assino. É sobre aquele recurso?' },
    { timestamp: '01:02', speaker: 'Advogado', text: 'Isso, é a petição de progressão de regime. Já montei toda a argumentação.' },
    { timestamp: '01:10', speaker: 'Detento', text: 'E o senhor acha que existe chance de deferimento?' },
    { timestamp: '01:16', speaker: 'Advogado', text: 'O comportamento está bom, já cumpriu o tempo mínimo. Acredito que existam boas chances.' },
    { timestamp: '01:25', speaker: 'Detento', text: 'Minha mãe está preocupada, doutor. Ela ligou para saber do andamento.' },
    { timestamp: '01:33', speaker: 'Advogado', text: 'Conversei com ela ontem. Expliquei a situação; ela ficou mais tranquila.' },
    { timestamp: '01:40', speaker: 'Detento', text: 'Agradeço, doutor. Ela é idosa e não compreende muito dessas questões.' },
    { timestamp: '01:48', speaker: 'Advogado', text: 'Sem problema. Agora, sobre o trabalho interno: você continua na oficina?' },
    { timestamp: '01:55', speaker: 'Detento', text: 'Sim, estou na marcenaria. O diretor informou que vai me conceder um certificado.' },
    { timestamp: '02:03', speaker: 'Advogado', text: 'Ótimo, isso contribui muito no processo. Vou anexar como prova de ressocialização.' },
    { timestamp: '02:12', speaker: 'Detento', text: 'E aquela questão do curso que eu solicitei? Conseguiu verificar?' },
    { timestamp: '02:18', speaker: 'Advogado', text: 'Sim, o curso de informática terá início no mês que vem. Já incluí seu nome na lista.' },
    { timestamp: '02:26', speaker: 'Detento', text: 'Ótimo! Isso vai me ajudar quando eu sair daqui.' },
    { timestamp: '02:33', speaker: 'Advogado', text: 'Com certeza. Educação e trabalho são diferenciais para a progressão.' },
    { timestamp: '02:40', speaker: 'Detento', text: 'Doutor, e sobre a visita da minha família? Minha esposa está com dificuldade para comparecer.' },
    { timestamp: '02:49', speaker: 'Advogado', text: 'Qual é a dificuldade? É questão de transporte?' },
    { timestamp: '02:55', speaker: 'Detento', text: 'É, ela reside longe e não tem como vir toda semana. Gostaria de verificar se é possível solicitar visita virtual.' },
    { timestamp: '03:04', speaker: 'Advogado', text: 'É possível, sim. Vou entrar com o pedido. A unidade já dispõe de estrutura para videoconferência.' },
    { timestamp: '03:12', speaker: 'Detento', text: 'Isso seria muito bom. As crianças estão com saudade.' },
    { timestamp: '03:18', speaker: 'Advogado', text: 'Vou agilizar o processo. Agora preciso ir, tenho outra audiência à tarde.' },
    { timestamp: '03:25', speaker: 'Detento', text: 'Está bem, doutor. Agradeço pela visita. Deus abençoe.' },
    { timestamp: '03:30', speaker: 'Advogado', text: 'Qualquer novidade envio recado. Fique bem, João.' },
    { timestamp: '03:35', speaker: 'Detento', text: 'Obrigado, doutor. Até a próxima.' },
  ],
  flaggedSegments: [
    {
      start: '00:18',
      end: '00:24',
      text: 'A encomenda que a gente conversou chegou?',
      reason: 'Possível uso de código — "encomenda" e "pacote" podem indicar entrega de material ilícito.',
    },
    {
      start: '00:31',
      end: '00:38',
      text: 'O pacote vai ser recebido no dia combinado então.',
      reason: 'Confirmação de recebimento com linguagem codificada.',
    },
  ],
};

/** Structured canonical analysis for REC-00129 */
const CANONICAL_ANALYSIS_REC00129 = {
  recordId: 'REC-00129',
  generatedAt: '18/02/2026 15:00',
  sections: [
    {
      id: 'metadata',
      title: 'Metadados Gerais',
      icon: 'info',
      fields: [
        { label: 'Tipo de interação', value: 'Atendimento jurídico presencial' },
        { label: 'Contexto', value: 'Conversa entre advogado e detento em unidade prisional' },
        { label: 'Duração aproximada', value: '3min 35s' },
      ],
    },
    {
      id: 'participants',
      title: 'Participantes',
      icon: 'users',
      fields: [
        {
          label: 'Detento',
          children: [
            { label: 'Nome', value: 'João' },
            { label: 'Vínculo', value: 'Interno' },
            { label: 'Atividade interna atual', value: 'Marcenaria / oficina' },
          ],
        },
        {
          label: 'Advogado',
          children: [
            { label: 'Tipo', value: 'Advogado de defesa' },
            { label: 'Nome', value: 'Não informado' },
          ],
        },
      ],
    },
    {
      id: 'topic_1',
      title: 'Andamento Processual',
      icon: 'gavel',
      fields: [
        {
          label: 'Audiência',
          children: [
            { label: 'Tipo', value: 'Audiência de processo penal' },
            { label: 'Status', value: 'Marcada' },
            { label: 'Data relativa', value: 'Semana que vem' },
          ],
        },
        {
          label: 'Processo',
          children: [
            { label: 'Status geral', value: 'Em andamento' },
            {
              label: 'Termos ambíguos identificados',
              risk: true,
              children: [
                {
                  label: '"encomenda" / "pacote"',
                  value: 'Interpretado pelo advogado como pacote de documentos processuais',
                  risk: true,
                },
                {
                  label: 'Risco potencial',
                  value: 'Termo ambíguo — deve ser monitorado por correlação com outros dados.',
                  risk: true,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'summary',
      title: 'Resumo Semântico',
      icon: 'clipboard-list',
      fields: [
        {
          label: 'Foco jurídico',
          value:
            'Audiência marcada, petição de progressão de regime em preparo. Necessidade de assinatura de documentos na próxima visita.',
        },
        {
          label: 'Foco social',
          value: 'Mãe tranquilizada pelo advogado. Esposa com dificuldade de deslocamento; pedido de visita virtual solicitado.',
        },
      ],
    },
  ],
};

/** Audit logs for REC-00129 */
const AUDIT_LOGS_REC00129: MockAuditLog[] = [
  {
    id: 'ev1',
    recordId: 'REC-00129',
    userId: 'system',
    user: { id: 'system', name: 'IA (processamento)', roles: [UserRole.analyst] },
    action: 'Registro marcado como Alerta de IA com score 0.92',
    previousStatus: AnalysisStatus.uploaded,
    nextStatus: AnalysisStatus.flagged_ai,
    notes: null,
    createdAt: new Date('2026-02-16T08:00:00'),
  },
  {
    id: 'ev2',
    recordId: 'REC-00129',
    userId: 'mock-u2',
    user: { id: 'mock-u2', name: 'Pedro Rocha', roles: [UserRole.analyst] },
    action: 'Análise iniciada — status alterado para Em Análise Humana',
    previousStatus: AnalysisStatus.flagged_ai,
    nextStatus: AnalysisStatus.under_review,
    notes: null,
    createdAt: new Date('2026-02-17T09:00:00'),
  },
  {
    id: 'ev3',
    recordId: 'REC-00129',
    userId: 'mock-u2',
    user: { id: 'mock-u2', name: 'Pedro Rocha', roles: [UserRole.analyst] },
    action: 'Alteração Confirmada',
    previousStatus: AnalysisStatus.under_review,
    nextStatus: AnalysisStatus.confirmed_human,
    notes: 'Identificado uso de gírias codificadas para "entrega"',
    createdAt: new Date('2026-02-18T14:30:00'),
  },
  {
    id: 'ev4',
    recordId: 'REC-00129',
    userId: 'mock-u1',
    user: { id: 'mock-u1', name: 'Ana Silva', roles: [UserRole.supervisor, UserRole.admin] },
    action: 'Editou texto canônico',
    previousStatus: null,
    nextStatus: null,
    notes: null,
    createdAt: new Date('2026-02-19T10:30:00'),
  },
];

/** Audit logs for REC-00128 */
const AUDIT_LOGS_REC00128: MockAuditLog[] = [
  {
    id: 'ev5',
    recordId: 'REC-00128',
    userId: 'system',
    user: { id: 'system', name: 'IA (processamento)', roles: [UserRole.analyst] },
    action: 'Registro marcado como Alerta de IA com score 0.97',
    previousStatus: AnalysisStatus.uploaded,
    nextStatus: AnalysisStatus.flagged_ai,
    notes: null,
    createdAt: new Date('2026-02-14T16:00:00'),
  },
  {
    id: 'ev6',
    recordId: 'REC-00128',
    userId: 'mock-u6',
    user: { id: 'mock-u6', name: 'Juliana Neves', roles: [UserRole.analyst] },
    action: 'Alteração Confirmada',
    previousStatus: AnalysisStatus.flagged_ai,
    nextStatus: AnalysisStatus.confirmed_human,
    notes: null,
    createdAt: new Date('2026-02-16T11:00:00'),
  },
  {
    id: 'ev7',
    recordId: 'REC-00128',
    userId: 'mock-u1',
    user: { id: 'mock-u1', name: 'Ana Silva', roles: [UserRole.supervisor, UserRole.admin] },
    action: 'Aprovação definitiva',
    previousStatus: AnalysisStatus.confirmed_human,
    nextStatus: AnalysisStatus.approved,
    notes: 'Evidências suficientes para retenção permanente',
    createdAt: new Date('2026-02-17T10:00:00'),
  },
];

export const MOCK_RECORDS: MockRecord[] = [
  {
    id: 'REC-00129',
    detaineeName: 'João Silva',
    detaineeCode: '10234',
    detaineeCell: '3B',
    visitorName: 'Maria Souza',
    visitorType: VisitorType.ATENDIMENTO_JURIDICO,
    unit: 'Unidade A',
    vivencia: 'Alfa',
    equipment: 'Dual Channel',
    blobUrl: null,
    mediaAvailable: true,
    recordedAt: new Date('2026-02-15T10:00:00'),
    uploadedAt: new Date('2026-02-15T11:30:00'),
    uploadedById: 'mock-u3',
    uploadedBy: { id: 'mock-u3', name: 'Carlos Lima' },
    analysisStatus: AnalysisStatus.confirmed_human,
    retentionStatus: RetentionStatus.retention_extended,
    aiScore: 0.92,
    analystId: 'mock-u2',
    analystDecision: 'COM_ALTERACAO',
    analystJustification: 'Identificado uso de gírias codificadas para "entrega"',
    analysisConfirmedAt: new Date('2026-02-18T14:30:00'),
    supervisorId: null,
    supervisorDecision: null,
    supervisorJustification: null,
    supervisorDecidedAt: null,
    transcription: TRANSCRIPTION_REC00129,
    canonicalAnalysis: CANONICAL_ANALYSIS_REC00129,
    archivedAt: null,
    archivedById: null,
    archivedBy: null,
    auditLogs: AUDIT_LOGS_REC00129,
    createdAt: new Date('2026-02-15T11:30:00'),
    updatedAt: new Date('2026-02-19T10:30:00'),
  },
  {
    id: 'REC-00128',
    detaineeName: 'Pedro Costa',
    detaineeCode: '20456',
    detaineeCell: '1A',
    visitorName: 'Fernanda Lima',
    visitorType: VisitorType.ATENDIMENTO_JURIDICO,
    unit: 'Unidade D',
    vivencia: 'Bravo',
    equipment: 'Mono',
    blobUrl: null,
    mediaAvailable: true,
    recordedAt: new Date('2026-02-14T14:00:00'),
    uploadedAt: new Date('2026-02-14T15:00:00'),
    uploadedById: 'mock-u3',
    uploadedBy: { id: 'mock-u3', name: 'Carlos Lima' },
    analysisStatus: AnalysisStatus.approved,
    retentionStatus: RetentionStatus.permanent_retention,
    aiScore: 0.97,
    analystId: 'mock-u6',
    analystDecision: 'COM_ALTERACAO',
    analystJustification: null,
    analysisConfirmedAt: new Date('2026-02-16T11:00:00'),
    supervisorId: 'mock-u1',
    supervisorDecision: 'approved',
    supervisorJustification: 'Evidências suficientes para retenção permanente',
    supervisorDecidedAt: new Date('2026-02-17T10:00:00'),
    transcription: null,
    canonicalAnalysis: null,
    archivedAt: null,
    archivedById: null,
    archivedBy: null,
    auditLogs: AUDIT_LOGS_REC00128,
    createdAt: new Date('2026-02-14T15:00:00'),
    updatedAt: new Date('2026-02-17T10:00:00'),
  },
  {
    id: 'REC-00127',
    detaineeName: 'Ana Paula',
    detaineeCode: '30789',
    detaineeCell: '2C',
    visitorName: 'Roberto Melo',
    visitorType: VisitorType.ATENDIMENTO_JURIDICO,
    unit: 'Unidade C',
    vivencia: 'Charlie',
    equipment: 'Dual Channel',
    blobUrl: null,
    mediaAvailable: true,
    recordedAt: new Date('2026-02-13T09:00:00'),
    uploadedAt: new Date('2026-02-13T10:00:00'),
    uploadedById: 'mock-u5',
    uploadedBy: { id: 'mock-u5', name: 'Marcos Teixeira' },
    analysisStatus: AnalysisStatus.flagged_ai,
    retentionStatus: RetentionStatus.retention_standard,
    aiScore: 0.88,
    analystId: null,
    analystDecision: null,
    analystJustification: null,
    analysisConfirmedAt: null,
    supervisorId: null,
    supervisorDecision: null,
    supervisorJustification: null,
    supervisorDecidedAt: null,
    transcription: null,
    canonicalAnalysis: null,
    archivedAt: null,
    archivedById: null,
    archivedBy: null,
    auditLogs: [],
    createdAt: new Date('2026-02-13T10:00:00'),
    updatedAt: new Date('2026-02-13T10:00:00'),
  },
  {
    id: 'REC-00126',
    detaineeName: 'Carlos Mendes',
    detaineeCode: '40123',
    detaineeCell: '4D',
    visitorName: 'Patrícia Fonseca',
    visitorType: VisitorType.VISITA_SOCIAL_PRESENCIAL,
    unit: 'Unidade B',
    vivencia: 'Delta',
    equipment: 'Mono',
    blobUrl: null,
    mediaAvailable: true,
    recordedAt: new Date('2026-02-12T16:00:00'),
    uploadedAt: new Date('2026-02-12T17:00:00'),
    uploadedById: 'mock-u3',
    uploadedBy: { id: 'mock-u3', name: 'Carlos Lima' },
    analysisStatus: AnalysisStatus.under_review,
    retentionStatus: RetentionStatus.retention_standard,
    aiScore: 0.78,
    analystId: null,
    analystDecision: null,
    analystJustification: null,
    analysisConfirmedAt: null,
    supervisorId: null,
    supervisorDecision: null,
    supervisorJustification: null,
    supervisorDecidedAt: null,
    transcription: null,
    canonicalAnalysis: null,
    archivedAt: null,
    archivedById: null,
    archivedBy: null,
    auditLogs: [],
    createdAt: new Date('2026-02-12T17:00:00'),
    updatedAt: new Date('2026-02-12T17:00:00'),
  },
  {
    id: 'REC-00125',
    detaineeName: 'Marcos Oliveira',
    detaineeCode: '50678',
    detaineeCell: '5E',
    visitorName: 'Luiz Henrique',
    visitorType: VisitorType.ATENDIMENTO_JURIDICO,
    unit: 'Unidade A',
    vivencia: 'Isolamento',
    equipment: 'Dual Channel',
    blobUrl: null,
    mediaAvailable: true,
    recordedAt: new Date('2026-02-11T11:00:00'),
    uploadedAt: new Date('2026-02-11T12:00:00'),
    uploadedById: 'mock-u3',
    uploadedBy: { id: 'mock-u3', name: 'Carlos Lima' },
    analysisStatus: AnalysisStatus.clean,
    retentionStatus: RetentionStatus.retention_standard,
    aiScore: 0.12,
    analystId: null,
    analystDecision: null,
    analystJustification: null,
    analysisConfirmedAt: null,
    supervisorId: null,
    supervisorDecision: null,
    supervisorJustification: null,
    supervisorDecidedAt: null,
    transcription: null,
    canonicalAnalysis: null,
    archivedAt: null,
    archivedById: null,
    archivedBy: null,
    auditLogs: [],
    createdAt: new Date('2026-02-11T12:00:00'),
    updatedAt: new Date('2026-02-11T12:00:00'),
  },
  {
    id: 'REC-00124',
    detaineeName: 'Ricardo Santos',
    detaineeCode: '60345',
    detaineeCell: '6F',
    visitorName: 'Camila Torres',
    visitorType: VisitorType.VISITA_SOCIAL_VIRTUAL,
    unit: 'Unidade E',
    vivencia: 'Triagem',
    equipment: 'Desconhecido',
    blobUrl: null,
    mediaAvailable: true,
    recordedAt: new Date('2026-02-10T08:00:00'),
    uploadedAt: new Date('2026-02-10T09:00:00'),
    uploadedById: 'mock-u5',
    uploadedBy: { id: 'mock-u5', name: 'Marcos Teixeira' },
    analysisStatus: AnalysisStatus.processing_ai,
    retentionStatus: RetentionStatus.retention_standard,
    aiScore: null,
    analystId: null,
    analystDecision: null,
    analystJustification: null,
    analysisConfirmedAt: null,
    supervisorId: null,
    supervisorDecision: null,
    supervisorJustification: null,
    supervisorDecidedAt: null,
    transcription: null,
    canonicalAnalysis: null,
    archivedAt: null,
    archivedById: null,
    archivedBy: null,
    auditLogs: [],
    createdAt: new Date('2026-02-10T09:00:00'),
    updatedAt: new Date('2026-02-10T09:00:00'),
  },
  {
    id: 'REC-00123',
    detaineeName: 'José Ferreira',
    detaineeCode: '70901',
    detaineeCell: '7G',
    visitorName: 'André Barbosa',
    visitorType: VisitorType.ATENDIMENTO_JURIDICO,
    unit: 'Unidade B',
    vivencia: 'Alfa',
    equipment: 'Mono',
    blobUrl: null,
    mediaAvailable: false,
    recordedAt: new Date('2026-02-09T15:00:00'),
    uploadedAt: new Date('2026-02-09T16:00:00'),
    uploadedById: 'mock-u3',
    uploadedBy: { id: 'mock-u3', name: 'Carlos Lima' },
    analysisStatus: AnalysisStatus.rejected_human,
    retentionStatus: RetentionStatus.retention_standard,
    aiScore: 0.45,
    analystId: 'mock-u2',
    analystDecision: 'SEM_ALTERACAO',
    analystJustification: 'Conversa sem conteúdo suspeito',
    analysisConfirmedAt: new Date('2026-02-11T10:00:00'),
    supervisorId: null,
    supervisorDecision: null,
    supervisorJustification: null,
    supervisorDecidedAt: null,
    transcription: null,
    canonicalAnalysis: null,
    archivedAt: null,
    archivedById: null,
    archivedBy: null,
    auditLogs: [],
    createdAt: new Date('2026-02-09T16:00:00'),
    updatedAt: new Date('2026-02-11T10:00:00'),
  },
  {
    id: 'REC-00122',
    detaineeName: 'Antônio Nunes',
    detaineeCode: '80567',
    detaineeCell: '8H',
    visitorName: 'Beatriz Carvalho',
    visitorType: VisitorType.VISITA_SOCIAL_PRESENCIAL,
    unit: 'Unidade C',
    vivencia: 'Bravo',
    equipment: 'Dual Channel',
    blobUrl: null,
    mediaAvailable: false,
    recordedAt: new Date('2026-02-08T10:00:00'),
    uploadedAt: new Date('2026-02-08T11:00:00'),
    uploadedById: 'mock-u3',
    uploadedBy: { id: 'mock-u3', name: 'Carlos Lima' },
    analysisStatus: AnalysisStatus.rejected_supervisor,
    retentionStatus: RetentionStatus.retention_standard,
    aiScore: 0.61,
    analystId: 'mock-u4',
    analystDecision: 'COM_ALTERACAO',
    analystJustification: null,
    analysisConfirmedAt: new Date('2026-02-10T09:00:00'),
    supervisorId: 'mock-u1',
    supervisorDecision: 'rejected_supervisor',
    supervisorJustification: 'Evidências insuficientes para escalada',
    supervisorDecidedAt: new Date('2026-02-11T15:00:00'),
    transcription: null,
    canonicalAnalysis: null,
    archivedAt: null,
    archivedById: null,
    archivedBy: null,
    auditLogs: [],
    createdAt: new Date('2026-02-08T11:00:00'),
    updatedAt: new Date('2026-02-11T15:00:00'),
  },
  {
    id: 'REC-00121',
    detaineeName: 'Fernando Alves',
    detaineeCode: '11234',
    detaineeCell: '2A',
    visitorName: 'Sônia Ramos',
    visitorType: VisitorType.VISITA_SOCIAL_VIRTUAL,
    unit: 'Unidade A',
    vivencia: 'Delta',
    equipment: 'Dual Channel',
    blobUrl: null,
    mediaAvailable: true,
    recordedAt: new Date('2026-02-07T13:00:00'),
    uploadedAt: new Date('2026-02-07T14:00:00'),
    uploadedById: 'mock-u3',
    uploadedBy: { id: 'mock-u3', name: 'Carlos Lima' },
    analysisStatus: AnalysisStatus.uploaded,
    retentionStatus: RetentionStatus.retention_standard,
    aiScore: null,
    analystId: null,
    analystDecision: null,
    analystJustification: null,
    analysisConfirmedAt: null,
    supervisorId: null,
    supervisorDecision: null,
    supervisorJustification: null,
    supervisorDecidedAt: null,
    transcription: null,
    canonicalAnalysis: null,
    archivedAt: null,
    archivedById: null,
    archivedBy: null,
    auditLogs: [],
    createdAt: new Date('2026-02-07T14:00:00'),
    updatedAt: new Date('2026-02-07T14:00:00'),
  },
  {
    id: 'REC-00120',
    detaineeName: 'José Pereira',
    detaineeCode: '90123',
    detaineeCell: '9I',
    visitorName: 'Mariana Costa',
    visitorType: VisitorType.ATENDIMENTO_JURIDICO,
    unit: 'Unidade F',
    vivencia: 'Charlie',
    equipment: 'Mono',
    blobUrl: null,
    mediaAvailable: true,
    recordedAt: new Date('2026-02-01T09:00:00'),
    uploadedAt: new Date('2026-02-01T10:00:00'),
    uploadedById: 'mock-u5',
    uploadedBy: { id: 'mock-u5', name: 'Marcos Teixeira' },
    analysisStatus: AnalysisStatus.confirmed_human,
    retentionStatus: RetentionStatus.archived,
    aiScore: 0.71,
    analystId: 'mock-u2',
    analystDecision: 'COM_ALTERACAO',
    analystJustification: null,
    analysisConfirmedAt: new Date('2026-02-15T09:00:00'),
    supervisorId: null,
    supervisorDecision: null,
    supervisorJustification: null,
    supervisorDecidedAt: null,
    transcription: null,
    canonicalAnalysis: null,
    archivedAt: new Date('2026-02-17T14:00:00'),
    archivedById: 'mock-u1',
    archivedBy: { id: 'mock-u1', name: 'Ana Silva', roles: [UserRole.supervisor, UserRole.admin] },
    auditLogs: [
      {
        id: 'ev8',
        recordId: 'REC-00120',
        userId: 'mock-u1',
        user: { id: 'mock-u1', name: 'Ana Silva', roles: [UserRole.supervisor, UserRole.admin] },
        action: 'Registro arquivado',
        previousStatus: AnalysisStatus.confirmed_human,
        nextStatus: null,
        notes: 'retention_status alterado para Arquivado',
        createdAt: new Date('2026-02-17T14:00:00'),
      },
    ],
    createdAt: new Date('2026-02-01T10:00:00'),
    updatedAt: new Date('2026-02-17T14:00:00'),
  },
];

// ─── Mock AI result (used by AiService when USE_MOCK_AI=true) ─────────────────
export const MOCK_TRANSCRIPTION_RESULT = {
  ...TRANSCRIPTION_REC00129,
  canonicalAnalysis: CANONICAL_ANALYSIS_REC00129 as Record<string, unknown>,
};
